# Generated by Django 3.2.5 on 2021-10-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('heading1', models.CharField(max_length=300)),
                ('content1', models.TextField()),
                ('heading2', models.CharField(max_length=300)),
                ('content2', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
