# Generated by Django 3.2.7 on 2021-11-12 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211106_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
