# Generated by Django 3.2.7 on 2021-11-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='other_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
