# Generated by Django 3.2.7 on 2021-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('check1', models.CharField(max_length=50)),
                ('check2', models.CharField(max_length=50)),
                ('check3', models.CharField(max_length=50)),
                ('check4', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
